//created on: 25 oct 2025
package rule1

//list any import classes here.
import java.util.List;
import java.util.Collections;
import java.util.Comparator;
import java.util.ArrayList;

import dominioECG.Persona;
import dominioECG.RegistroECG;
import dominioECG.Onda;
import dominioECG.OndaP;
import dominioECG.OndaQ;
import dominioECG.OndaR;
import dominioECG.OndaS;
import dominioECG.OndaT;
import dominioECG.Ciclo;
import dominioECG.Intervalo;
import dominioECG.TipoIntervalo;
import dominioECG.Complejo;
import dominioECG.RitmoCardiaco;
import dominioECG.Diagnostico;
import dominioECG.Bradicardia;

//declare any global variables here
global java.util.concurrent.atomic.AtomicInteger cicloContador;



rule "Print y Crear Registros Persona"
	no-loop true
    when
        $p: Persona();
    then
    	java.util.List<RegistroECG> registros = $p.getRegistroECG();
        for (RegistroECG reg : registros) {
	        System.out.println("Registro ID: " + reg.getIdRegistro());
	        System.out.println("Insertando registro clase: " + reg.getClass().getName());
	        insert(reg);
    	}
end

declare RegistroProcesado
    registroId : String
end

rule "Insertar ondas"
    when
        $r: RegistroECG();
        not RegistroProcesado( registroId == $r.getIdRegistro() )
    then
	    System.out.println("Insertamos ondas del registro con ID: " + $r.getIdRegistro() + ".");
	    List<Onda> ondas= $r.getOndasRegistro();

	    for (int i = 0; i < ondas.size() - 1; i++) {
	        insert(ondas.get(i));
	        //System.out.println(ondas.get(i).getCicloPertenece() == null);
	    }
		insert(new RegistroProcesado($r.getIdRegistro()));
end

//rule "Ver ondasQ"
//		no-loop true
//	when
//		$ondaQ : dominioECG.OndaQ();
//	then
//		System.out.println("OndaQ con start_time: " + $ondaQ.getStart_time());
//			
//end

rule "Crear ciclos"
		no-loop true
	when
        // Capturamos un registro para usarlo en todos los filtros
        $registro : RegistroECG()
        
        
        //Contamos numero de ciclos:
        //$numCiclos : Number() from accumulate (
		//	Ciclo( registroPertenece == $registro ),
		//	count( 1 )
		//)
	    
		// Encontramos OndaP
        // Debe ser del registro, sin ciclo asociado. Guardamos el start time y el end time para hacer 
        //comprobaciones con ondaQ
        $p : OndaP(
                registroPertenece == $registro, // Debe pertenecer a este $registro
                cicloPertenece == null,
                $finp : end_time
              )
        
        // Encontramos OndaQ (margen 70-120ms desde inicio OndaP)
       	$q : OndaQ(
                registroPertenece == $registro, // Mismo registro
                cicloPertenece == null,
                start_time >= $finp + 70,
	            start_time <= $finp + 110,
	            $finq : end_time 
              )
              
        // Encontramos OndaR (margen Q-R: ±5ms)
        $r : OndaR(
                registroPertenece == $registro, // Mismo registro
                cicloPertenece == null,
                start_time == $finq,
                $finr : end_time
              )
              
        // Encontramos OndaS (margen R-S: ±5ms) 
        $s : OndaS(
                registroPertenece == $registro, // Mismo registro
                cicloPertenece == null,
                start_time == $finr,
                $fins : end_time
              )
        
        // Encontramos OndaT (margen S-T: ±5ms)
        $t : OndaT(
                registroPertenece == $registro, // Mismo registro
                cicloPertenece == null,
                start_time >= $fins + 120,
	            start_time <= $fins + 160
              )     
         
	then	
		//System.out.println($numCiclos.intValue());	
		int nCiclos = cicloContador.incrementAndGet();
        System.out.println(" Creando Ciclo " + nCiclos + " para el registro " + $registro.getIdRegistro() + ".");
        
		Ciclo ciclo = new Ciclo();
		
		ciclo.setWaveP($p);
		ciclo.setWaveQ($q);
		ciclo.setWaveR($r);
		ciclo.setWaveS($s);
		ciclo.setWaveT($t);
		ciclo.setCycle_number(nCiclos);
		
		ciclo.setRegistroPertenece($registro);
		
		modify($p){setCicloPertenece(ciclo)};
		modify($q){setCicloPertenece(ciclo)};
		modify($r){setCicloPertenece(ciclo)};
		modify($s){setCicloPertenece(ciclo)};
		modify($t){setCicloPertenece(ciclo)};
		
		//Modificamos tambien registro, ya que le tenemos que meter el registro
		modify($registro){addCiclo(ciclo)};
		
				
		//Insertamos ciclo
		insert(ciclo);
end


rule "Crear intervalos PP Persona" //Dos ciclos
    when
    	$r: RegistroECG()
    	$p1 : OndaP(
	        registroPertenece == $r, // Comprueba que pertenece a $r
	        cicloPertenece != null,
	        $nciclo : cicloPertenece.cycle_number 
	    )
	    $p2 : OndaP(
	        registroPertenece == $r,
	        cicloPertenece != null,
	        cicloPertenece.cycle_number == $nciclo + 1 
	    )
    then
	    System.out.println("Creacion intervalo PP para ciclos: " + $nciclo + " y "+ $p2.getCicloPertenece().getCycle_number() + " del registro: " + $r.getIdRegistro());
	    Intervalo intervaloPP = new Intervalo($p1.getStart_time(), $p2.getStart_time(), TipoIntervalo.PP);
	    intervaloPP.setRegistroPertenece($r);
	    insert(intervaloPP);
end

rule "Crear intervalos RR Persona" //Dos ciclos
    when
    	$r: RegistroECG()
    	$r1 : OndaP(
	        registroPertenece == $r, // Comprueba que pertenece a $r
	        cicloPertenece != null,
	        $nciclo : cicloPertenece.cycle_number 
	    )
	    $r2 : OndaP(
	        registroPertenece == $r,
	        cicloPertenece != null,
	        cicloPertenece.cycle_number == $nciclo + 1 
	    )
    then
	    System.out.println("Creacion intervalo RR para ciclos: " + $nciclo + " y "+ $r2.getCicloPertenece().getCycle_number() + " del registro: " + $r.getIdRegistro());
	    Intervalo intervaloRR = new Intervalo($r1.getStart_time(), $r2.getStart_time(), TipoIntervalo.RR);
	    intervaloRR.setRegistroPertenece($r);
	    insert(intervaloRR);
end

rule "Crear intervalos PR Persona" //Dos ciclos
    when
    	$r: RegistroECG()
    	$p : OndaP(
            registroPertenece == $r, // Debe pertenecer a este $registro
            cicloPertenece != null,
            $nciclo : cicloPertenece.cycle_number
          )
    	$wR: OndaR(
    		registroPertenece == $r,
    		cicloPertenece != null,
    		cicloPertenece.cycle_number == $nciclo
    	)
    then
	    System.out.println("Creacion intervalo PR para ciclo: " + $nciclo + " del registro: " + $r.getIdRegistro());
	    Intervalo intervaloPR = new Intervalo($p.getStart_time(), $wR.getStart_time(), TipoIntervalo.PR);
	    intervaloPR.setRegistroPertenece($r);
	    insert(intervaloPR);
end


rule "Crear intervalos QT Persona" //Dos ciclos
    when
    	$r: RegistroECG()
    	$q : OndaQ(
                registroPertenece == $r, // Debe pertenecer a este $registro
                cicloPertenece != null,
                $nciclo : cicloPertenece.cycle_number
              )
    	$t: OndaT(
    		registroPertenece == $r,
    		cicloPertenece != null,
    		cicloPertenece.cycle_number == $nciclo
    	)
    then
	    System.out.println("Creacion intervalo QT para ciclo: " + $nciclo + " del registro: " + $r.getIdRegistro());
	    Intervalo intervaloQT = new Intervalo($q.getStart_time(), $t.getEnd_time(), TipoIntervalo.QT);
	    intervaloQT.setRegistroPertenece($r);
	    insert(intervaloQT);
end


rule "Crear intervalos ST Persona"
    when
    	$r: RegistroECG()
    	$s : OndaS(
                registroPertenece == $r, // Debe pertenecer a este $registro
                cicloPertenece != null,
                $nciclo : cicloPertenece.cycle_number
              )
    	$t: OndaT(
    		registroPertenece == $r,
    		cicloPertenece != null,
    		cicloPertenece.cycle_number == $nciclo
    	)
    then
	    System.out.println("Creacion intervalo ST para ciclo: " + $nciclo + " del registro: " + $r.getIdRegistro());
	    Intervalo intervaloST = new Intervalo($s.getEnd_time(), $t.getStart_time(), TipoIntervalo.ST);
	    intervaloST.setRegistroPertenece($r);
	    insert(intervaloST);
end

rule "Crear intervalos TP Persona" //Dos ciclos
    when
    	$r: RegistroECG()
    	$t : OndaP(
                registroPertenece == $r, // Debe pertenecer a este $registro
                cicloPertenece != null,
                $nciclo : cicloPertenece.cycle_number
              )
    	$p: OndaP(
    		registroPertenece == $r,
    		cicloPertenece != null,
    		cicloPertenece.cycle_number == $nciclo+1
    	)
    then
	    System.out.println("Creacion intervalo TP para ciclos: " + $nciclo + " y "+ $p.getCicloPertenece().getCycle_number() + " del registro: " + $r.getIdRegistro());
	    Intervalo intervaloTP = new Intervalo($t.getStart_time(), $p.getStart_time(), TipoIntervalo.TP);
	    intervaloTP.setRegistroPertenece($r);
	    insert(intervaloTP);
end

rule "Crear complejo QRS"
	when
	    $r: RegistroECG()
    	$q : OndaQ(
            registroPertenece == $r, // Debe pertenecer a este $registro
            cicloPertenece != null,
            $nciclo : cicloPertenece.cycle_number
        )
        $wR: OndaR(
    		registroPertenece == $r,
    		cicloPertenece != null,
    		cicloPertenece.cycle_number == $nciclo
    	)
    	$s : OndaS(
            registroPertenece == $r, // Debe pertenecer a este $registro
            cicloPertenece != null,
            cicloPertenece.cycle_number == $nciclo
          )
	then
		System.out.println("Creacion complejo QRS del ciclo: " + $nciclo + " del registro: " + $r.getIdRegistro());
	    
	    List<Onda> ondas = new ArrayList<>();
        ondas.add($q);
        ondas.add($wR);
        ondas.add($s);

        int tiempoInicio = $q.getStart_time();
        int tiempoFin = $s.getEnd_time();

        Complejo qrs = new Complejo(ondas, tiempoInicio, tiempoFin);
        qrs.setRegistroAsociado($r);
        insert(qrs);
end

rule "Crear Frecuencia Cardiaca"
	when
		$r: RegistroECG()
		accumulate (Intervalo(tipoIntervalo == TipoIntervalo.RR, registroPertenece == $r, $dur : duracion),
				    $promRR : average($dur)
				)   
	then
			double bpm = 60000/($promRR);
			System.out.println("Ritmo cardiaco del registro: " + $r.getIdRegistro() + " = " + bpm);
			RitmoCardiaco rc = new RitmoCardiaco(bpm, $r);
			insert(rc);
end

rule "Asignar Bradicardia Severa"
	when
		$r: RegistroECG();
		$rc: RitmoCardiaco(registroAsignado == $r,
						   valor <= 40)
	then
		String nombreDiagnostico = new String("Bradicardia Severa");
		String descripcion = new String("Detectada bradicardia sinusal SEVERA con respecto al registro: " + $r.getIdRegistro() + " por un ritmo cardiaco cuya frecuencia es inferior a 40 latidos/minuto en reposo: " + $rc.getValor());
		Bradicardia bradi = new Bradicardia(descripcion, nombreDiagnostico);
		bradi.setRegistroAsociado($r);
		insert(bradi);
		
end

rule "Asignar Bradicardia no Severo"
	when
		$r: RegistroECG();
		$rc: RitmoCardiaco(registroAsignado == $r,
						   valor > 40,
						   valor < 60)
	then
		String nombreDiagnostico = new String("Bradicardia no Severa");
		String descripcion = new String("Detectada bradicardia sinusal con respecto al registro: " + $r.getIdRegistro() + " por un ritmo cardiaco cuya frecuencia es inferior a 60 latidos/minuto en reposo: " + $rc.getValor());
		Bradicardia bradi = new Bradicardia(descripcion, nombreDiagnostico);
		bradi.setRegistroAsociado($r);
		insert(bradi);
end
		